"""auto update

Revision ID: d837e0f81350
Revises: 022ad59ca639
Create Date: 2026-04-21 22:01:00.178823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd837e0f81350'
down_revision: Union[str, Sequence[str], None] = '022ad59ca639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_files', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('app_files', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_files', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_files', 'updated_at')
    op.drop_column('app_files', 'created_at')
    op.drop_column('app_files', 'user_id')
    # ### end Alembic commands ###